title: Czas Zapłaty
description: Oficjalna strona modyfikacji do gry Gothic
theme: null
layouts_dir: ./server/templates
includes_dir: ./server/templates
paginate: 4
paginate_path: "/:num"
permalink: /:year/:month/:day/:title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      categories: "newsy"
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: "category"
  -
    scope:
      path: "download"
      type: "pages"
    values:
      layout: "redirect"
  -
    scope:
      path: "gallery"
      type: "pages"
    values:
      layout: "gallery-album"
collections:
  category:
    output: true
plugins:
  - github-pages